<?php
/** @var $block \Magento\Framework\View\Element\Template */
$order = $block->getParentBlock()->getOrder();
foreach ($order->getAllVisibleItems() as $item):
    $options = $item->getProductOptions();
    if (!empty($options['options'])):
        foreach ($options['options'] as $option):
            if ($option['option_type'] == 'character_limit'): ?>
                <div>
                    <strong><?php echo $block->escapeHtml($option['label']) ?>:</strong>
                    <?php echo $block->escapeHtml($option['value']) ?>
                </div>
            <?php endif;
        endforeach;
    endif;
endforeach;
