<?php

use Yash\US22\Model\Popup;
/** @var \Magento\Framework\View\Element\Template $block */
$popup = $block->getData('view_model')->getPopup();

$timeout = (int) $popup->getTimeout();
$mycontent = $popup instanceof Popup ? $popup->getContent() : $popup;

?>

<div data-bind="mageInit: {
        'Yash_US22/js/popup': {
            'timeout': '<?= $timeout ?>',
            'content': '<?= 'This is a popup content' ?>'
        }}">
</div>
